### ISSUE TITLE
'build' not executed with new version of angular-devkit/build-angular (0.1100.2)

### ISSUE THREAD

**Issue by slungtibco** [hashicorp/prebuild-webpack-plugin#21]
The `build` function of this plugin is not executed when upgrading to the latest **angular-devkit/build-angular** ("_@angular-devkit/build-angular": "~0.1100.2_") and running `ng build`.
Probably related to a new version of Webpack that is being used?

Workaround was to downgrade **angular-devkit/build-angular** to `~0.901.6`.
Why doesn't it work with the latest build-angular?

**Comment by jescalan** [comment]
I don't know, this is an issue you'd need to figure out with your angular build situation - the plugin is tested and works perfectly well normally.
