### ISSUE TITLE
`watch` never runs under next.js

### ISSUE THREAD

**Issue by endquote** [hashicorp/prebuild-webpack-plugin#8]
Thanks for this plugin, I'm trying it out to parse some files before build on a next.js project. I think I'm missing something, though.

My setup is below. The `build` step runs fine, but `watch` doesn't run when I change one of the matched files.

I noticed the note about `compilationNameFilter` in the docs and added that, but it doesn't seem to have any impact. I tried `dev` as well as `client`. I see both `server` and `client` in `compilation.name` at different times.

```
config.plugins.push(
  new PrebuildPlugin({
    build: (compiler, compilation, matchedFiles) => {
      console.log("build", compilation.name, matchedFiles);
      buildData(matchedFiles);
    },
    watch: (compiler, compilation, changedFile) => {
      console.log("watch", compilation.name, matchedFiles);
      buildData(matchedFiles);
    },
    files: {
      pattern: "**/data/+(projects|strings).yaml",
      options: {},
      addFilesAsDependencies: true
    }
    // compilationNameFilter: "server"
  })
);
```

**Comment by endquote** [comment]
User error. One callback was using `matchedFiles` and the other was using `changedFile`.

**Comment by jescalan** [comment]
👍🏼thanks for the update, glad you got it working!
